import Link from "next/link";
import { ArrowLeft, Download, Upload } from "lucide-react";
import { uploadSpreadsheet } from "@/app/admin/(protected)/importy/actions";

const errors: Record<string, string> = { missing: "Wybierz plik.", FILE_TOO_LARGE: "Plik jest za duży. Limit to 5 MB.", UNSUPPORTED_FILE: "Obsługiwane są wyłącznie pliki CSV i XLSX.", MALFORMED_XLSX: "Plik XLSX jest uszkodzony albo ma nieobsługiwaną strukturę.", EMPTY_FILE: "Plik nie zawiera danych.", TOO_MANY_COLUMNS: "Plik ma zbyt wiele kolumn.", TOO_MANY_ROWS: "Plik ma więcej niż 2000 wierszy.", };

export default async function NewImportPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const query = await searchParams;
  return <div className="space-y-5"><Link href="/admin/importy" className="inline-flex min-h-11 items-center gap-2 rounded-md px-2 text-sm font-bold text-brand-strong hover:bg-brand-soft"><ArrowLeft aria-hidden="true" size={18} />Wróć do importów</Link><header><p className="text-sm font-bold text-brand-strong">Źródła danych</p><h1 className="mt-1 text-3xl font-bold">Nowy import</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Wczytaj plik, sprawdź podgląd, dopasuj kolumny i przygotuj kandydatów do ręcznej weryfikacji.</p></header>{query.error ? <p role="alert" className="rounded-lg border border-urgent/30 bg-urgent-soft/40 p-3 text-sm font-semibold">{errors[query.error] ?? "Nie udało się odczytać pliku."}</p> : null}<section className="rounded-lg border border-border bg-white p-4 sm:p-6"><form action={uploadSpreadsheet} className="space-y-4"><label className="block text-sm font-semibold">Plik CSV lub XLSX<input required type="file" name="file" accept=".csv,.xlsx,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" className="mt-2 block min-h-12 w-full rounded-lg border border-border bg-white px-3 py-2 text-sm" /></label><ul className="space-y-1 text-sm text-muted-foreground"><li>Limit pliku: 5 MB, do 2000 wierszy i 80 kolumn.</li><li>Pierwszy wiersz powinien zawierać nagłówki; jeden wiersz oznacza jedną placówkę.</li><li>Wiele kategorii rozdziel średnikiem. Nie scalaj komórek.</li><li>Formuły, makra i osadzone skrypty nie są wykonywane.</li></ul><button type="submit" className="inline-flex min-h-11 items-center gap-2 rounded-lg bg-brand px-4 text-sm font-bold text-[#10231e]"><Upload aria-hidden="true" size={17} />Wczytaj i pokaż podgląd</button></form></section><section className="rounded-lg border border-border bg-white p-4 sm:p-5"><h2 className="text-lg font-bold">Szablon importu</h2><p className="mt-1 text-sm text-muted-foreground">Pobierz przykładowe nagłówki bez prawdziwych danych osób.</p><a href="/admin/importy/szablon.csv" className="mt-3 inline-flex min-h-11 items-center gap-2 rounded-lg border border-border px-4 text-sm font-bold text-brand-strong hover:bg-brand-soft"><Download aria-hidden="true" size={17} />Pobierz szablon CSV</a></section></div>;
}
