import { requirePermission } from "@/lib/admin/session";
import { prisma } from "@/lib/prisma";
import { PlaceAccessReviewForm } from "@/components/admin/organizations/place-access-review-form";
import { reviewOrganizationRegistration } from "./actions";

export default async function OrganizationRegistrationsPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  await requirePermission("MANAGE_ORGANIZATIONS");
  const query = await searchParams;
  const [registrations, pendingEmailRegistrations, organizations, accessRequests] = await Promise.all([
    prisma.organizationRegistration.findMany({ where: { status: "PENDING_REVIEW" }, include: { adminUser: true, possibleOrganization: true }, orderBy: { createdAt: "asc" } }),
    prisma.organizationRegistration.findMany({ where: { status: "EMAIL_PENDING" }, select: { id: true, organizationName: true, applicantName: true, applicantEmail: true, createdAt: true }, orderBy: { createdAt: "asc" } }),
    prisma.organization.findMany({ where: { active: true }, orderBy: { name: "asc" }, select: { id: true, name: true } }),
    prisma.placeAccessRequest.findMany({ where: { status: "PENDING" }, include: { requestingUser: true, place: { select: { name: true, addressLine: true } } }, orderBy: { createdAt: "asc" } }),
  ]);
  return <div className="space-y-5">
    <header><p className="text-sm font-bold text-brand-strong">Dostęp organizacji</p><h1 className="mt-1 text-3xl font-bold">Rejestracje organizacji</h1><p className="mt-2 text-sm text-muted-foreground">Weryfikacja nie przyznaje automatycznie dostępu do żadnej placówki.</p></header>
    {query.error === "organization-required" ? <p role="alert" className="rounded-lg border border-urgent/30 bg-urgent-soft/40 p-3 text-sm font-semibold">Wybierz istniejącą organizację albo utwórz nową przed zatwierdzeniem.</p> : null}
    {query.error === "organization-duplicate" ? <p role="alert" className="rounded-lg border border-urgent/30 bg-urgent-soft/40 p-3 text-sm font-semibold">Znaleziono organizację o identycznej nazwie. Wybierz ją ręcznie zamiast tworzyć duplikat.</p> : null}
    {registrations.length ? <div className="space-y-4">{registrations.map((registration) => <article key={registration.id} className="rounded-lg border border-border bg-white p-4 sm:p-5"><div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(260px,0.7fr)]"><div><h2 className="text-lg font-bold">{registration.organizationName}</h2><dl className="mt-3 grid gap-2 text-sm sm:grid-cols-2"><div><dt className="text-xs text-muted-foreground">Osoba</dt><dd>{registration.applicantName}</dd></div><div><dt className="text-xs text-muted-foreground">E-mail</dt><dd className="break-all">{registration.applicantEmail}</dd></div><div><dt className="text-xs text-muted-foreground">Organizacja e-mail</dt><dd className="break-all">{registration.organizationEmail}</dd></div><div><dt className="text-xs text-muted-foreground">Data</dt><dd>{new Intl.DateTimeFormat("pl-PL", { dateStyle: "medium" }).format(registration.createdAt)}</dd></div></dl>{registration.possibleOrganization ? <p className="mt-3 rounded-md bg-brand-soft/50 p-3 text-sm"><strong>Możliwe dopasowanie:</strong> {registration.possibleOrganization.name}</p> : null}</div><form action={reviewOrganizationRegistration} className="space-y-3"><input type="hidden" name="id" value={registration.id} /><label className="block text-sm font-semibold">Organizacja<select name="organizationId" defaultValue={registration.possibleOrganizationId ?? ""} className="mt-1 min-h-11 w-full rounded-lg border border-border bg-white px-3 font-normal"><option value="">Nie przypisuj jeszcze</option>{organizations.map((organization) => <option key={organization.id} value={organization.id}>{organization.name}</option>)}<option value="__new__">Utwórz nową organizację z danych zgłoszenia</option></select></label><textarea name="rejectionReason" placeholder="Powód odrzucenia (opcjonalnie)" className="min-h-20 w-full rounded-lg border border-border px-3 py-2 text-sm" /><div className="flex flex-wrap gap-2"><button name="decision" value="approve" className="inline-flex min-h-11 items-center rounded-lg bg-brand px-4 text-sm font-bold">Zatwierdź</button><button name="decision" value="reject" className="inline-flex min-h-11 items-center rounded-lg border border-border px-4 text-sm font-bold">Odrzuć</button></div></form></div></article>)}</div> : <section className="rounded-lg border border-border bg-white p-6"><h2 className="font-bold">Brak oczekujących rejestracji</h2><p className="mt-2 text-sm text-muted-foreground">Nowe zgłoszenia pojawią się tutaj po potwierdzeniu e-maila.</p></section>}
    {pendingEmailRegistrations.length ? <section className="space-y-3"><h2 className="text-xl font-bold">Oczekują na potwierdzenie e-maila</h2><p className="text-sm text-muted-foreground">Te zgłoszenia są zapisane, ale nie mogą jeszcze trafić do weryfikacji organizacji.</p><div className="space-y-3">{pendingEmailRegistrations.map((registration) => <article key={registration.id} className="rounded-lg border border-border bg-white p-4"><h3 className="font-bold">{registration.organizationName}</h3><p className="mt-1 text-sm">{registration.applicantName} · <span className="break-all">{registration.applicantEmail}</span></p><p className="mt-2 text-xs text-muted-foreground">Zgłoszenie z {new Intl.DateTimeFormat("pl-PL", { dateStyle: "medium" }).format(registration.createdAt)}. Po potwierdzeniu e-maila pojawi się w sekcji do weryfikacji.</p></article>)}</div></section> : null}
    {accessRequests.length ? <section className="space-y-4"><h2 className="text-xl font-bold">Prośby o dostęp do placówek</h2>{accessRequests.map((request) => <article key={request.id} className="rounded-lg border border-border bg-white p-4"><h3 className="font-bold">{request.place.name}</h3><p className="mt-1 text-sm text-muted-foreground">{request.requestingUser.displayName} · {request.requestingUser.email}</p><p className="mt-3 text-sm">{request.message || "Bez dodatkowej wiadomości."}</p><PlaceAccessReviewForm id={request.id} /></article>)}</section> : null}
  </div>;
}
